version: '3'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: image
    ports:
      - 8080:80
    volumes:
      - .:/app
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: dbs
    networks:
      - network

  db:
    image: mysql:8
    ports:
      - 6033:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dbs
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - network
        
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
    networks:
      - network

networks:
   network:

volumes:
   db-data:
